"""adding 2 columns to user class model

Revision ID: 5524d81e8c66
Revises: 2622b78882df
Create Date: 2021-09-23 08:08:35.864198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5524d81e8c66'
down_revision = '2622b78882df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
